# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f51aa3ade2ce07d7ca473130918a047aa1188f1ff0aee30ed0b991fc3b567accd9166fc438f9a00f0d9779747b90466cdcb9eaa9c16986dc3a7abb547eb95ca9

test:
  secret_key_base: c831661dd38dcbfb79730471ae49565b84b10fc2e93f23988648800b749de4ad0748ec4b24672b5965aeb82c74fc0610fc7d46dbc1b2a2fee8c5bfb9c9af0c50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
